const products = [
  {
    id: 1,
    title: "کتانی ونس مردانه Ashoes کد 1516",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/product-1662-thumb_lg.jpg",
  },
  {
    id: 2,
    title: "کتانی زنانه yezzy450 کد 1508",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/product-1653-thumb_lg.jpg",
  },
  {
    id: 3,
    title: "صندل مردانه fitness کد 1512",
    category: "جدیدترین",
    price: "۱.۷۹۸.۰۰۰",
    img: "./images/product-1654-thumb_lg.jpg",
  },
  {
    id: 4,
    title: "کتانی ونس بچگانه fashion کد 1515",
    category: "جدیدترین",
    price: "۷۹۸.۰۰۰",
    img: "./images/product-1658-thumb_lg.jpg",
  },
  {
    id: 5,
    title: "کتانی ونس مردانه Ashoes کد 1516",
    category: "جدیدترین",
    price: "۱.۱۹۸.۰۰۰",
    img: "./images/product-1661-thumb_lg.jpg",
  },
  {
    id: 6,
    title: "ونس زنانه A-SHOES طرح خرسی کد 1517",
    category: "جدیدترین",
    price: "۱.۱۹۸.۰۰۰",
    img: "./images/product-1663-thumb_lg.jpg",
  },
  {
    id: 7,
    title: "کتانی بچگانه SPORT کد 1519",
    category: "جدیدترین",
    price: "۷۹۸.۰۰۰",
    img: "./images/product-1665-thumb_lg.jpg",
  },
  {
    id: 8,
    title: "کتانی مردانه YEZZY350 کد 1522",
    category: "جدیدترین",
    price: "۱.۴۹۸.۰۰۰",
    img: "./images/product-1667-thumb_lg.jpg",
  },
];

const other = [
  {
    id: 7,
    title: "نیم بوت تیمبرلند زنونه  کد5",
    category: "discounted",
    price: 12000000,
    img: "./images/variety-191-thumb_lg.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
];
export default products;
