const products = [
  {
    id: 1,
    title: "کتانی ونس مردانه Ashoes کد 1516",
    category: "جدیدترین",
    price: "898000",
    img: "./images/product-1662-thumb_lg.jpg",
  },
  {
    id: 2,
    title: "کتانی زنانه yezzy450 کد 1508",
    category: "جدیدترین",
    price: "898000",
    img: "./images/product-1653-thumb_lg.jpg",
  },
  {
    id: 3,
    title: "صندل مردانه fitness کد 1512",
    category: "جدیدترین",
    price: "۱.798000",
    img: "./images/product-1654-thumb_lg.jpg",
  },
  {
    id: 4,
    title: "کتانی ونس بچگانه fashion کد 1515",
    category: "جدیدترین",
    price: "798000",
    img: "./images/product-1658-thumb_lg.jpg",
  },
  {
    id: 5,
    title: "کتانی ونس مردانه Ashoes کد 1516",
    category: "جدیدترین",
    price: "1198000",
    img: "./images/product-1661-thumb_lg.jpg",
  },
  {
    id: 6,
    title: "ونس زنانه A-SHOES طرح خرسی کد 1517",
    category: "جدیدترین",
    price: "1198000",
    img: "./images/product-1663-thumb_lg.jpg",
  },
  {
    id: 7,
    title: "کتانی بچگانه SPORT کد 1519",
    category: "جدیدترین",
    price: "798000",
    img: "./images/product-1665-thumb_lg.jpg",
  },
  {
    id: 8,
    title: "کتانی مردانه YEZZY350 کد 1522",
    category: "جدیدترین",
    price: "1498000",
    img: "./images/product-1667-thumb_lg.jpg",
  },
];

export const MenProducts = [
  {
    id: 1,
    title: "کتانی مردانه نایک ایرفورس کد 1573",
    category: "جدیدترین",
    price: 548000,
    images: [
      "../../images/men/1/1.jpg",
      "../../images/men/1/2.jpg",
      "../../images/men/1/3.jpg",
      "../../images/men/1/4.jpg",
    ],
    img: "../../images/men/1.jpg",
    inventory: 5,
    colors: ["سفید", "سورمه‌ای مشکی", "سورمه‌ای", "طوسی"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "روزمره و کالج مردانه",
  },
  {
    id: 2,
    title: "کتانی مردانه AX2 کد 1569",
    category: "جدیدترین",
    price: "698000",
    images: [
      "../../images/men/2/1.jpg",
      "../../images/men/2/2.jpg",
      "../../images/men/2/3.jpg",
      "../../images/men/2/4.jpg",
      "../../images/men/2/5.jpg",
    ],
    img: "../../images/men/2/2.jpg",
    inventory: 5,
    colors: [
      "سورمه‌ای",
      "مشکی تمام",
      "مشکی طوسی قرمز",
      "مشکی طوسی نارنجی",
      "مشکی طوسی",
    ],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "روزمره و کالج مردانه",
  },
  {
    id: 3,
    title: "کتانی مردانه نایک جردن 13 کد 1567",
    category: "جدیدترین",
    price: "598000",
    images: ["../../images/men/3/1.jpg"],
    img: "../../images/men/3/3.jpg",
    inventory: 5,
    colors: ["سفید طوسی"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "روزمره و کالج مردانه",
  },
  {
    id: 4,
    title: "کتانی مردانه جردن XXVII کد 1566",
    category: "جدیدترین",
    price: 2598000,
    images: [
      "../../images/men/4/1.jpg",
      "../../images/men/4/2.jpg",
      "../../images/men/4/3.jpg",
    ],
    img: "../../images/men/4/4.jpg",
    inventory: 5,
    colors: ["سفید مشکی قرمز", "مشکی سفید قرمز", "یشمی"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "کتانی و ورزشی مردانه",
  },
  {
    id: 5,
    title: "کتانی مردانه ونس زارا کد 1563",
    category: "جدیدترین",
    price: 558000,
    images: [
      "../../images/men/5/1.jpg",
      "../../images/men/5/2.jpg",
      "../../images/men/5/3.jpg",
      "../../images/men/5/4.jpg",
    ],
    img: "../../images/men/5/5.jpg",
    inventory: 5,
    colors: ["خاکی", "سفید", "طوسی", "مشکی"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "کتانی و ورزشی مردانه",
  },
  {
    id: 6,
    title: "کتانی مردانه بامبو کشی کد 1561",
    category: "جدیدترین",
    price: 658000,
    images: ["../../images/men/6/6.jpg"],
    img: "../../images/men/6/6.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "کتانی و ورزشی مردانه",
  },
  {
    id: 7,
    title: "کتانی ونس بندی بامبو کد 1558",
    category: "جدیدترین",
    price: 658000,
    images: ["../../images/men/7/7.jpg"],
    img: "../../images/men/7/7.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "مجلسی و رسمی مردانه",
  },
  {
    id: 8,
    title: "کتانی مردانه نیوبالانس BT کد 1557",
    category: "جدیدترین",
    price: 688000,
    images: ["../../images/men/8/8.jpg"],
    img: "../../images/men/8/8.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "مجلسی و رسمی مردانه",
  },
  {
    id: 9,
    title: "کتانی مردانه نیوبالانس BT کد 1557",
    category: "جدیدترین",
    price: 558000,
    images: ["../../images/men/9/9.jpg"],
    img: "../../images/men/9/9.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "مجلسی و رسمی مردانه",
  },
  {
    id: 10,
    title: "کتانی مردانه WOLF کد 1555",
    category: "جدیدترین",
    price: 848000,
    images: ["../../images/men/10/10.jpg"],
    img: "../../images/men/10/10.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "مجلسی و رسمی مردانه",
  },
  {
    id: 11,
    title: "کتانی مردانه ادیداس ZX کد 1554",
    category: "جدیدترین",
    price: 548000,
    images: ["../../images/men/11/11.jpg"],
    img: "../../images/men/11/11.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "بوت و نیم‌بوت مردانه",
  },
  {
    id: 12,
    title: "کتانی مردانه سالامون جورابی کد 1552",
    category: "جدیدترین",
    price: 598000,
    images: ["../../images/men/12/12.jpg"],
    img: "../../images/men/12/12.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "بوت و نیم‌بوت مردانه",
  },
  {
    id: 13,
    title: "کتانی مردانه امو جورابی کد 1551",
    category: "جدیدترین",
    price: 528000,
    images: ["../../images/men/13/13.jpg"],
    img: "../../images/men/13/13.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "بوت و نیم‌بوت مردانه",
  },
  {
    id: 14,
    title: "کتانی مردانه برشکا لژدار کد 1550",
    category: "جدیدترین",
    price: 688000,
    images: ["../../images/men/14/14.jpg"],
    img: "../../images/men/14/14.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "بزرگ‌‌پا مردانه",
  },
  {
    id: 15,
    title: "کتانی مردانه ادیداس FANTESY کد 1547",
    category: "جدیدترین",
    price: 628000,
    images: ["../../images/men/15/15.jpg"],
    img: "../../images/men/15/15.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "بزرگ‌‌پا مردانه",
  },
  {
    id: 16,
    title: "کتانی مردانه KMH کد 1541",
    category: "جدیدترین",
    price: 1198000,
    images: ["../../images/men/16/16.jpg"],
    img: "../../images/men/16/16.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "بزرگ‌‌پا مردانه",
  },
  {
    id: 17,
    title: "کتانی ونس مردانه پرچمی کد 1535",
    category: "جدیدترین",
    price: 898000,
    images: ["../../images/men/17/17.jpg"],
    img: "../../images/men/17/17.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "کتانی و ورزشی مردانه",
  },
  {
    id: 18,
    title: "کتانی ونس مردانه کد 1524",
    category: "جدیدترین",
    price: 898000,
    images: ["../../images/men/18/18.jpg"],
    img: "../../images/men/18/18.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "کتانی و ورزشی مردانه",
  },
  {
    id: 19,
    title: "کتانی مردانه YEZZY350 کد 1522",
    category: "جدیدترین",
    price: 1498000,
    images: ["../../images/men/19/19.jpg"],
    img: "../../images/men/19/19.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "کتانی و ورزشی مردانه",
  },
  {
    id: 20,
    title: "کتانی ونس مردانه Ashoes کد 1516",
    category: "جدیدترین",
    price: 1198000,
    images: ["../../images/men/20/20.jpg"],
    img: "../../images/men/20/20.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "روزمره و کالج مردانه",
  },
  {
    id: 21,
    title: "کتانی ونس لژدار کد 1513",
    category: "جدیدترین",
    price: 8980002,
    images: ["../../images/men/21/21.jpg"],
    img: "../../images/men/21/21.jpg",
    inventory: 5,
    colors: ["طوسی", "سرمه‌ای", "سفید"],
    sizes: ["38", "39", "40", "41", "42", "43"],
    type: "running",
    gender: "men",
    grouping: "روزمره و کالج مردانه",
  },
];

export const WomenProducts = [
  {
    id: 1,
    title: "کتانی زنانه HERMES کد 1571",
    category: "جدیدترین",
    price: "698000",
    img: "./images/women/1.jpg",
  },
  {
    id: 2,
    title: "کتانی زنانه AX2کد 1568",
    category: "جدیدترین",
    price: "۱.698000",
    img: "./images/women/2.jpg",
  },
  {
    id: 3,
    title: "کتانی زنانه جورابی CCBVV کد 1545",
    category: "جدیدترین",
    price: "558000",
    img: "./images/women/3.jpg",
  },
  {
    id: 4,
    title: "کتانی ونس زنانه طرح بغل گلدوزی کد 1544",
    category: "جدیدترین",
    price: "528000",
    img: "./images/women/4.jpg",
  },
  {
    id: 5,
    title: "کتانی ساقدار زنانه ANAJUM کد 1540",
    category: "جدیدترین",
    price: "898000",
    img: "./images/women/5.jpg",
  },
  {
    id: 6,
    title: "کتانی ونس 90 کد 1538",
    category: "جدیدترین",
    price: "1198000",
    img: "./images/women/6.jpg",
  },
  {
    id: 7,
    title: "کتانی زنانه ونس تک چسب کد1537",
    category: "جدیدترین",
    price: "1198000",
    img: "./images/women/7.jpg",
  },
  {
    id: 8,
    title: "کتانی جورابی ساقدار کد 1533",
    category: "جدیدترین",
    price: "898000",
    img: "./images/women/8.jpg",
  },
  {
    id: 9,
    title: "کتانی جورابی rostory کد 1532",
    category: "جدیدترین",
    price: "898000",
    img: "./images/women/9.jpg",
  },
  {
    id: 10,
    title: "کتانی زنانه طرح لوزی کد 1531",
    category: "جدیدترین",
    price: "678000",
    img: "./images/women/10.jpg",
  },
  {
    id: 11,
    title: "کتانی ونس زنانه نایک ایرمکس کد 1530",
    category: "جدیدترین",
    price: "768000",
    img: "./images/women/11.jpg",
  },
  {
    id: 12,
    title: "کتانی ونس زنانه الکساندر مکویین کد 1529",
    category: "جدیدترین",
    price: "628000",
    img: "./images/women/12.jpg",
  },
  {
    id: 13,
    title: "کتانی زنانه ادیداس توری کد 1528",
    category: "جدیدترین",
    price: "778000",
    img: "./images/women/13.jpg",
  },
  {
    id: 14,
    title: "کتانی زنانه ونس tezz کد 1527",
    category: "جدیدترین",
    price: "798000",
    img: "./images/women/14.jpg",
  },
  {
    id: 15,
    title: "ونس زنانه A-SHOES طرح ساده کد 1518",
    category: "جدیدترین",
    price: "1198000",
    img: "./images/women/15.jpg",
  },
  {
    id: 16,
    title: "ونس زنانه A-SHOES طرح خرسی کد 1517",
    category: "جدیدترین",
    price: "1198000",
    img: "./images/women/16.jpg",
  },
  {
    id: 17,
    title: "کتانی زنانه makliniot طرح shougu کد 1510",
    category: "جدیدترین",
    price: "898000",
    img: "./images/women/17.jpg",
  },
  {
    id: 18,
    title: "کتانی زنانه maklinit طرح N کد 1509",
    category: "جدیدترین",
    price: "898000",
    img: "./images/women/18.jpg",
  },
  {
    id: 19,
    title: "کتانی زنانه yezzy450 کد 1508",
    category: "جدیدترین",
    price: "898000",
    img: "./images/women/19.jpg",
  },
  {
    id: 20,
    title: "کتانی زنانه maklinit طرح fashionکد 1507",
    category: "جدیدترین",
    price: "898000",
    img: "./images/women/20.jpg",
  },
  {
    id: 21,
    title: "کتانی زنانه maklinit طرح v کد 1506",
    category: "جدیدترین",
    price: "898000",
    img: "./images/women/21.jpg",
  },
];

export const ChildrenProducts = [
  {
    id: 1,
    title: "کتانی زنانه HERMES کد 1571",
    category: "جدیدترین",
    price: "698000",
    img: "./images/women/1.jpg",
  },
];

const other = [
  {
    id: 7,
    title: "نیم بوت تیمبرلند زنونه  کد5",
    category: "discounted",
    price: 12000000,
    img: "./images/variety-191-thumb_lg.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
];

export default products;
