const products = [
  {
    id: 1,
    title: "کتانی ونس مردانه Ashoes کد 1516",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/product-1662-thumb_lg.jpg",
  },
  {
    id: 2,
    title: "کتانی زنانه yezzy450 کد 1508",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/product-1653-thumb_lg.jpg",
  },
  {
    id: 3,
    title: "صندل مردانه fitness کد 1512",
    category: "جدیدترین",
    price: "۱.۷۹۸.۰۰۰",
    img: "./images/product-1654-thumb_lg.jpg",
  },
  {
    id: 4,
    title: "کتانی ونس بچگانه fashion کد 1515",
    category: "جدیدترین",
    price: "۷۹۸.۰۰۰",
    img: "./images/product-1658-thumb_lg.jpg",
  },
  {
    id: 5,
    title: "کتانی ونس مردانه Ashoes کد 1516",
    category: "جدیدترین",
    price: "۱.۱۹۸.۰۰۰",
    img: "./images/product-1661-thumb_lg.jpg",
  },
  {
    id: 6,
    title: "ونس زنانه A-SHOES طرح خرسی کد 1517",
    category: "جدیدترین",
    price: "۱.۱۹۸.۰۰۰",
    img: "./images/product-1663-thumb_lg.jpg",
  },
  {
    id: 7,
    title: "کتانی بچگانه SPORT کد 1519",
    category: "جدیدترین",
    price: "۷۹۸.۰۰۰",
    img: "./images/product-1665-thumb_lg.jpg",
  },
  {
    id: 8,
    title: "کتانی مردانه YEZZY350 کد 1522",
    category: "جدیدترین",
    price: "۱.۴۹۸.۰۰۰",
    img: "./images/product-1667-thumb_lg.jpg",
  },
];

export const MenProducts = [
  {
    id: 1,
    title: "کتانی مردانه نایک ایرفورس کد 1573",
    category: "جدیدترین",
    price: "۵۴۸.۰۰۰",
    img: "./images/men/1.jpg",
  },
  {
    id: 2,
    title: "کتانی مردانه AX2 کد 1569",
    category: "جدیدترین",
    price: "۱.۶۹۸.۰۰۰",
    img: "./images/men/2.jpg",
  },
  {
    id: 3,
    title: "کتانی مردانه نایک جردن 13 کد 1567",
    category: "جدیدترین",
    price: "۲.۵۹۸.۰۰۰",
    img: "./images/men/3.jpg",
  },
  {
    id: 4,
    title: "کتانی مردانه جردن XXVII کد 1566",
    category: "جدیدترین",
    price: "۲.۵۹۸.۰۰۰",
    img: "./images/men/4.jpg",
  },
  {
    id: 5,
    title: "کتانی مردانه ونس زارا کد 1563",
    category: "جدیدترین",
    price: "۵۵۸.۰۰۰",
    img: "./images/men/5.jpg",
  },
  {
    id: 6,
    title: "کتانی مردانه بامبو کشی کد 1561",
    category: "جدیدترین",
    price: "۶۵۸.۰۰۰",
    img: "./images/men/6.jpg",
  },
  {
    id: 7,
    title: "کتانی ونس بندی بامبو کد 1558",
    category: "جدیدترین",
    price: "۶۵۸.۰۰۰",
    img: "./images/men/7.jpg",
  },
  {
    id: 8,
    title: "کتانی مردانه نیوبالانس BT کد 1557",
    category: "جدیدترین",
    price: "۶۸۸.۰۰۰",
    img: "./images/men/8.jpg",
  },
  {
    id: 9,
    title: "کتانی مردانه نیوبالانس BT کد 1557",
    category: "جدیدترین",
    price: "۵۵۸.۰۰۰",
    img: "./images/men/8.jpg",
  },
  {
    id: 10,
    title: "کتانی مردانه WOLF کد 1555",
    category: "جدیدترین",
    price: "۸۴۸.۰۰۰",
    img: "./images/men/10.jpg",
  },
  {
    id: 11,
    title: "کتانی مردانه ادیداس ZX کد 1554",
    category: "جدیدترین",
    price: "۵۴۸.۰۰۰",
    img: "./images/men/11.jpg",
  },
  {
    id: 12,
    title: "کتانی مردانه سالامون جورابی کد 1552",
    category: "جدیدترین",
    price: "۵۹۸.۰۰۰",
    img: "./images/men/12.jpg",
  },
  {
    id: 13,
    title: "کتانی مردانه امو جورابی کد 1551",
    category: "جدیدترین",
    price: "۵۲۸.۰۰۰",
    img: "./images/men/13.jpg",
  },
  {
    id: 14,
    title: "کتانی مردانه برشکا لژدار کد 1550",
    category: "جدیدترین",
    price: "۶۸۸.۰۰۰",
    img: "./images/men/14.jpg",
  },
  {
    id: 15,
    title: "کتانی مردانه ادیداس FANTESY کد 1547",
    category: "جدیدترین",
    price: "۶۲۸.۰۰۰",
    img: "./images/men/15.jpg",
  },
  {
    id: 16,
    title: "کتانی مردانه KMH کد 1541",
    category: "جدیدترین",
    price: "۱.۱۹۸.۰۰۰",
    img: "./images/men/16.jpg",
  },
  {
    id: 17,
    title: "کتانی ونس مردانه پرچمی کد 1535",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/men/17.jpg",
  },
  {
    id: 18,
    title: "کتانی ونس مردانه کد 1524",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/men/18.jpg",
  },
  {
    id: 19,
    title: "کتانی مردانه YEZZY350 کد 1522",
    category: "جدیدترین",
    price: "۱.۴۹۸.۰۰۰",
    img: "./images/men/19.jpg",
  },
  {
    id: 20,
    title: "کتانی ونس مردانه Ashoes کد 1516",
    category: "جدیدترین",
    price: "۱.۱۹۸.۰۰۰",
    img: "./images/men/20.jpg",
  },
  {
    id: 21,
    title: "کتانی ونس لژدار کد 1513",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/men/21.jpg",
  },
];

export const WomenProducts = [
  {
    id: 1,
    title: "کتانی زنانه HERMES کد 1571",
    category: "جدیدترین",
    price: "۶۹۸.۰۰۰",
    img: "./images/women/1.jpg",
  },
  {
    id: 2,
    title: "کتانی زنانه AX2کد 1568",
    category: "جدیدترین",
    price: "۱.۶۹۸.۰۰۰",
    img: "./images/women/2.jpg",
  },
  {
    id: 3,
    title: "کتانی زنانه جورابی CCBVV کد 1545",
    category: "جدیدترین",
    price: "۵۵۸.۰۰۰",
    img: "./images/women/3.jpg",
  },
  {
    id: 4,
    title: "کتانی ونس زنانه طرح بغل گلدوزی کد 1544",
    category: "جدیدترین",
    price: "۵۲۸.۰۰۰",
    img: "./images/women/4.jpg",
  },
  {
    id: 5,
    title: "کتانی ساقدار زنانه ANAJUM کد 1540",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/women/5.jpg",
  },
  {
    id: 6,
    title: "کتانی ونس 90 کد 1538",
    category: "جدیدترین",
    price: "۱.۱۹۸.۰۰۰",
    img: "./images/women/6.jpg",
  },
  {
    id: 7,
    title: "کتانی زنانه ونس تک چسب کد1537",
    category: "جدیدترین",
    price: "۱.۱۹۸.۰۰۰",
    img: "./images/women/7.jpg",
  },
  {
    id: 8,
    title: "کتانی جورابی ساقدار کد 1533",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/women/8.jpg",
  },
  {
    id: 9,
    title: "کتانی جورابی rostory کد 1532",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/women/9.jpg",
  },
  {
    id: 10,
    title: "کتانی زنانه طرح لوزی کد 1531",
    category: "جدیدترین",
    price: "۶۷۸.۰۰۰",
    img: "./images/women/10.jpg",
  },
  {
    id: 11,
    title: "کتانی ونس زنانه نایک ایرمکس کد 1530",
    category: "جدیدترین",
    price: "۷۶۸.۰۰۰",
    img: "./images/women/11.jpg",
  },
  {
    id: 12,
    title: "کتانی ونس زنانه الکساندر مکویین کد 1529",
    category: "جدیدترین",
    price: "۶۲۸.۰۰۰",
    img: "./images/women/12.jpg",
  },
  {
    id: 13,
    title: "کتانی زنانه ادیداس توری کد 1528",
    category: "جدیدترین",
    price: "۷۷۸.۰۰۰",
    img: "./images/women/13.jpg",
  },
  {
    id: 14,
    title: "کتانی زنانه ونس tezz کد 1527",
    category: "جدیدترین",
    price: "۷۹۸.۰۰۰",
    img: "./images/women/14.jpg",
  },
  {
    id: 15,
    title: "ونس زنانه A-SHOES طرح ساده کد 1518",
    category: "جدیدترین",
    price: "۱.۱۹۸.۰۰۰",
    img: "./images/women/15.jpg",
  },
  {
    id: 16,
    title: "ونس زنانه A-SHOES طرح خرسی کد 1517",
    category: "جدیدترین",
    price: "۱.۱۹۸.۰۰۰",
    img: "./images/women/16.jpg",
  },
  {
    id: 17,
    title: "کتانی زنانه makliniot طرح shougu کد 1510",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/women/17.jpg",
  },
  {
    id: 18,
    title: "کتانی زنانه maklinit طرح N کد 1509",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/women/18.jpg",
  },
  {
    id: 19,
    title: "کتانی زنانه yezzy450 کد 1508",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/women/19.jpg",
  },
  {
    id: 20,
    title: "کتانی زنانه maklinit طرح fashionکد 1507",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/women/20.jpg",
  },
  {
    id: 21,
    title: "کتانی زنانه maklinit طرح v کد 1506",
    category: "جدیدترین",
    price: "۹۸۸.۰۰۰",
    img: "./images/women/21.jpg",
  },
];

export const ChildrenProducts = [
  {
    id: 1,
    title: "کتانی زنانه HERMES کد 1571",
    category: "جدیدترین",
    price: "۶۹۸.۰۰۰",
    img: "./images/women/1.jpg",
  },
]

const other = [
  {
    id: 7,
    title: "نیم بوت تیمبرلند زنونه  کد5",
    category: "discounted",
    price: 12000000,
    img: "./images/variety-191-thumb_lg.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
  {
    id: 7,
    title: "گوشی",
    category: "گوشی",
    price: 12000000,
    img: "./images/7.jpg",
  },
];

export default products;
